<?php

/**
 * @file
 * Module file for ereol_feed.
 */

use Drupal\ereol_feed\Controller\FrontpageController;
use Drupal\ereol_feed\Controller\ParagraphsController;

/**
 * Implements hook_menu().
 */
function ereol_feed_menu() {
  $items['ereol_feed/frontpage'] = [
    'page callback' => 'ereol_feed_frontpage_endpoint',
    'access arguments' => ['access content'],
  ];

  $items['ereol_feed/paragraphs/%'] = [
    'page callback' => 'ereol_feed_paragraphs_endpoint',
    'page arguments' => [2],
    'access arguments' => ['access content'],
  ];

  return $items;
}

/**
 * Frontpage endpoint.
 */
function ereol_feed_frontpage_endpoint() {
  $controller = new FrontpageController();
  $controller->index();
}

/**
 * Paragraphs endpoint.
 */
function ereol_feed_paragraphs_endpoint($type) {
  $controller = new ParagraphsController();
  $controller->index($type);
}
